version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.8
 build: 
  commands:
   - sam build
   - export BUCKET=f2020-a3-artifacts-1-bucket
   - sam package --s3-bucket $BUCKET --region us-east-1 --output-template-file outputtemplate.yml --debug
artifacts:
 type: zip
 files:
  - template.yml
  - outputtemplate.yml