# AWSTemplateFormatVersion: '2010-09-09'
# Transform: AWS::Serverless-2016-10-31
# Description: SAM Build template 
# Resources:
#  LF1:
#   Type: AWS::Serverless::Function
#   Properties:
#    Handler: index-photos.lambda_handler
#    Role: arn:aws:iam::456240511584:role/A3-lambda-admin
#    Runtime: python3.8
#    FunctionName: index-photos
#    MemorySize: 128
#    Timeout: 30
#    CodeUri: ./src #Directory the source file is
#  LF2:
#   Type: AWS::Serverless::Function
#   Properties:
#    Role: arn:aws:iam::456240511584:role/A3-lambda-admin
#    Handler: LF2-search.lambda_handler
#    Runtime: python3.8
#    FunctionName: LF2-cloudformation-test
#    MemorySize: 128
#    Timeout: 30
#    CodeUri: ./src #Directory the source file is
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:
 SampleFunction:
  Type: AWS::Serverless::Function
  Properties:
   Handler: index.lambda_handler
   Runtime: python3.8
   FunctionName: SamplePython
   CodeUri: ./src #Directory the source file is