AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Build template 
Resources:
  photoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: a3-b2-jars-cftest
  LF1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index-photos.lambda_handler
      Role: arn:aws:iam::456240511584:role/A3-lambda-admin
      Runtime: python3.8
      FunctionName: index-photos-cftest
      MemorySize: 128
      Timeout: 30
      CodeUri: ./src
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref photoBucket
            Events: s3:ObjectCreated:Put
  LF2:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::456240511584:role/A3-lambda-admin
      Handler: LF2-search.lambda_handler
      Runtime: python3.8
      FunctionName: search-photos-cftest
      MemorySize: 128
      Timeout: 30
      CodeUri: ./src