AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      FunctionName: SamplePython
      CodeUri: ./src #Directory the source file is
  LF1:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::456240511584:role/A3-lambda-admin
      FunctionName: index-photos
      MemorySize: 128
      Timeout: 30
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./src